import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Layout from "./src/components/Layout";
import { AuthProvider } from "./src/contexts/AuthContext";
import { CompanyProvider } from "./src/contexts/CompanyContext";
import { LocaleProvider } from "./src/i18n/LocaleProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full">{
        /* Layout handles page chrome (sidebar, header) and content area */
      }
      <LocaleProvider>
        <AuthProvider>
          <CompanyProvider>
            <Layout>{children}</Layout>
          </CompanyProvider>
        </AuthProvider>
      </LocaleProvider>
      </body>
    </html>
  );
}
